FROM mcr.microsoft.com/dotnet/core/runtime:3.1-buster-slim AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /src
COPY src/Demo.Services.ECS1/Demo.Services.ECS1.csproj ./Demo.Services.ECS1/
COPY src/Demo.Lib.Data/Demo.Lib.Data.csproj ./Demo.Lib.Data/
COPY nuget.config .
COPY proxycert.pem .
ENV SSL_CERT_FILE=/src/proxycert.pem

RUN dotnet restore "Demo.Services.ECS1/Demo.Services.ECS1.csproj"


COPY src/Demo.Services.ECS1/. ./Demo.Services.ECS1/
COPY src/Demo.Lib.Data/. ./Demo.Lib.Data/
WORKDIR /src
RUN dotnet build "Demo.Services.ECS1/Demo.Services.ECS1.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Demo.Services.ECS1/Demo.Services.ECS1.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet","Demo.Services.ECS1.dll"]